default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ahmadmirza
  password: 123456
  host: localhost

development:
  <<: *default
  database: recipe_sharing_development

test:
  <<: *default
  database: recipe_sharing_test

production:
  <<: *default
  database: recipe_sharing_production
